# Azure DevOps pipeline for Azure deployment

variables:
- group: terraform-project

trigger: none
  #branches:
    #include:
    #- main

stages:
- stage: Validate
  displayName: Validate
  jobs:
  - job: validate
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    # Azure Key Vault
    # Download Azure Key Vault secrets
    - task: AzureKeyVault@1
      inputs:
        ConnectedServiceName: $(service_name)
        keyVaultName: $(key_vault_name)
        secretsFilter: '*'
        runAsPreJob: false # Azure DevOps Services only
    
    # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ARM_SAS_TOKEN: $(SAStoken)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        commandOptions: '-backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(containername) -backend-config=key=$(terraformkey)'
        backendType: 'selfConfigured'

  # Validate
    - task: TerraformCLI@0
      displayName: Validate Config
      inputs:
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    
- stage: Plan
  displayName: Plan
  jobs:
  - job: plan
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    # Azure Key Vault
    # Download Azure Key Vault secrets
    - task: AzureKeyVault@1
      inputs:
        ConnectedServiceName: $(service_name)
        keyVaultName: $(key_vault_name)
        secretsFilter: '*'
        runAsPreJob: false # Azure DevOps Services only
  
    # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ARM_SAS_TOKEN: $(SAStoken)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        commandOptions: '-backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(containername) -backend-config=key=$(terraformkey)'
        backendType: 'selfConfigured'

  # Plan
    - task: TerraformCLI@0
      displayName: Plan Terraform Deployment
      env:
        ARM_SAS_TOKEN: $(SAStoken)
        ARM_CLIENT_ID: $(az-clientid)
        ARM_CLIENT_SECRET: $(terraform1)
        ARM_SUBSCRIPTION_ID: $(az-subscription1)
        ARM_TENANT_ID: $(az-tenantid)
      inputs:
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)'

# Approve
- stage: Approve
  displayName: Approve
  jobs:
  - job: approve
    displayName: Wait for approval
    pool: server
    steps: 
    - task: ManualValidation@0
      timeoutInMinutes: 60
      inputs:
        notifyUsers: 'bauerbrett1@gmail.com'
        instructions: 'Review the plan in the next hour'

- stage: Destroy
  displayName: Destroy
  jobs:
  - job: destroy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@0
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    # Azure Key Vault
    # Download Azure Key Vault secrets
    - task: AzureKeyVault@1
      inputs:
        ConnectedServiceName: $(service_name)
        keyVaultName: $(key_vault_name)
        secretsFilter: '*'
        runAsPreJob: false # Azure DevOps Services only

  # Init
    - task: TerraformCLI@0
      displayName: Initialize Terraform
      env:
        ARM_SAS_TOKEN: $(SAStoken)
      inputs:
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        commandOptions: '-backend-config=storage_account_name=$(storageaccount) -backend-config=container_name=$(containername) -backend-config=key=$(terraformkey)'
        backendType: 'selfConfigured'

  # Apply
    - task: TerraformCLI@0
      displayName: Destroy Terraform Deployment
      env:
        ARM_SAS_TOKEN: $(SAStoken)
        ARM_CLIENT_ID: $(az-clientid)
        ARM_CLIENT_SECRET: $(terraform1)
        ARM_SUBSCRIPTION_ID: $(az-subscription1)
        ARM_TENANT_ID: $(az-tenantid)
      inputs:
        command: 'Destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        commandOptions: '-auto-approve'